[project]
name = "heteroknockoffpy"
version = "0.3.2"
description = "Variable selection with knockoffs for heterogeneous continuous, count, and categorical data"
readme = "README.md"
authors = [
    { name = "Evan Mason" }
]
requires-python = ">=3.13"
dependencies = [
    "polars>=1.32,<2",
    "numpy>=1.26.0",
    "knockpy",
    "rpy2>=3.6.4",
    "pandas>=2.0.0,<3",
    "pyarrow>=23.0.0",
    "scikit-learn>=1.08",
    "statsmodels",
    "sympypl>=0.2.0",
    "torch>=2.6.7",
    "xgboost",
]

license = "Apache-2.0"
license-files = ["LICENSE"]

[project.optional-dependencies]
shap = ["shap"]

[build-system]
requires = ["uv_build>=0.11.23,<0.12"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "optuna>=4.9.0",
    "pytest>=9.0.3",
]
